pub(crate) mod arm64_codegenerator;
pub(crate) mod common;
pub(crate) mod internal;
pub(crate) mod linuxapi;
pub(crate) mod patch_amd64;
pub(crate) mod patch_arm64;
pub(crate) mod patch_trait;
pub(crate) mod utils;
pub(crate) mod winapi;
