name: PR Diff Coverage

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  diff-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
        with:
          toolchain: stable
          override: true

      - name: Install Tarpaulin
        run: cargo install cargo-tarpaulin --version 0.32.0 --force

      - name: Run Tarpaulin -> JSON summary
        run: |
            mkdir -p coverage
            cargo tarpaulin \
            --out Json \
            --output-dir coverage \
            -- --test-threads=1

      - name: Archive coverage JSON
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: coverage-summary
          path: coverage/coverage-summary.json
